name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup dev workspace so we can actually compile
      run: ./gradlew setupDevWorkspace
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload built file
      uses: actions/upload-artifact@v2
      with:
        name: FrogESPAddon
        path: ./build/libs/rootnet-frog-esp-*[!sources].jar
